version: "3"
services: 
  db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: clientDb
    ports:
      - "5432:5432"
  app: 
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
  client:
    image: node:20
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - "3001:3000"
    command: ["npm", "start"]
    depends_on:
      - app
