version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: clientDb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 20s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=clientDb
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ../frontend
    working_dir: /app
    volumes:
      - ../frontend:/app
    ports:
      - "3001:3000"
    environment:
      - PORT=3001
    command: ["npm", "start"]
    depends_on:
      - app
    networks:
      - clientmanager_default

networks:
  clientmanager_default:
    driver: bridge
