version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: clientDb
    ports:
      - "5432:5432"
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ../frontend
    working_dir: /app
    volumes:
      - ../frontend:/app
    ports:
      - "3001:3000"
    environment:
      - PORT=3001
    command: ["npm", "start"]
    depends_on:
      - app
